FROM node:iron-alpine3.21 AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY . .

FROM node:iron-alpine3.21
WORKDIR /app

COPY --from=builder /app . 

ENV NODE_ENV=production
EXPOSE 8000

CMD ["node", "src/cmd/index.js"]
