FROM node:iron-alpine3.21 AS deps
WORKDIR /app
RUN apk add --no-cache bash

COPY package.json package-lock.json ./
RUN npm install

FROM deps AS dev
WORKDIR /app

RUN npm install -g nodemon

COPY . .

EXPOSE 8000
CMD ["nodemon", "src/cmd/index.js"]

FROM node:iron-alpine3.21 AS prod
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY . .

ENV NODE_ENV=production
EXPOSE 8000
CMD ["node", "src/cmd/index.js"]
