name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed


jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Generate .env from secrets
        run: |
          sudo apt-get update && sudo apt-get install -y gettext
          envsubst < .env.example > .env
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          APP_PORT: ${{ secrets.APP_PORT }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          SWAGGER_PORT: ${{ secrets.SWAGGER_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Stop and Remove Old Containers
        run: make down-prod

      - name: Remove Old Docker Images
        run: |
          echo "Removing unused images..."
          docker image prune -af || true

          echo "Removing dangling build cache..."
          docker builder prune -af || true


      - name: Run Docker
        run: make up-prod